<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Morita.LP.Razor.Tests/**/*.cs" />
    <Content Remove="Morita.LP.Razor.Tests/**/*" />
    <None Remove="Morita.LP.Razor.Tests/**/*" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="8.0.19" />
  </ItemGroup>

</Project>
