name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Morita.LP.Razor.csproj

      - name: Build
        run: dotnet build Morita.LP.Razor.csproj -c Release --no-restore

      - name: Setup Flyctl
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: flyctl deploy --remote-only --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
